AWSTemplateFormatVersion: "2010-09-09"
Description: GitHub OIDC Provider template.
Parameters:
  GitHubOIDCProviderArn:
    Type: String
    Default: ""
    Description: If GitHub OIDC Provider already exists, set its ARN.
Conditions:
  GitHubOIDCProviderExists: !Equals
    - !Ref GitHubOIDCProviderArn
    - ""
Resources:
  GitHubOIDCProvider:
    Type: AWS::IAM::OIDCProvider
    Condition: GitHubOIDCProviderExists
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1
  GitHubActionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: docker-lambda-deployer
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: !If
                - GitHubOIDCProviderExists
                - !Ref GitHubOIDCProvider
                - !Ref GitHubOIDCProviderArn
            Condition:
              StringLike:
                token.actions.githubusercontent.com:sub: repo:heroween/docker-lambda-sample:*
      Policies:
        - PolicyName: docker-lambda-deploy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ecr:BatchCheckLayerAvailability
                  - ecr:CompleteLayerUpload
                  - ecr:InitiateLayerUpload
                  - ecr:PutImage
                  - ecr:UploadLayerPart
                Resource: arn:aws:ecr:ap-northeast-1::repository/lambda/*
              - Effect: Allow
                Action:
                  - lambda:PublishVersion
                  - lambda:UpdateFunctionCode
                  - lambda:UpdateAliases
                Resource: "*"
Outputs:
  GitHubActionsRole:
    Value: !GetAtt GitHubActionsRole.Arn
